name: bespoke
description: "A construction helper app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  auto_route: ^9.2.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  flex_color_scheme: ^8.0.2
#  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  auto_route_generator: ^9.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

