name: bespoke
description: "A construction helper app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  auto_route: ^9.2.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  flex_color_scheme: ^8.0.2
  cloud_firestore_odm: ^1.0.0-dev.88
  flutter_form_builder: ^9.7.0
  form_builder_validators: ^11.1.1
  flutter_svg: ^2.0.17
  table_calendar: ^3.1.3
  intl: ^0.19.0
  flutter_launcher_icons: ^0.14.3
#  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  cloud_firestore_odm_generator: ^1.0.0-dev.89
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  auto_route_generator: ^9.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/bespoke_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "path/to/image.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/2.0x
    - assets/icons/3.0x
    - assets/icons/4.0x
    - assets/fonts/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBoldItalic.ttf
          weight: 700
          style: italic
