// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXGby8vxkBXL4j945w55p-Kt9ooN0afX4',
    appId: '1:1004288477701:web:1c88ea49c228fb10efaa6c',
    messagingSenderId: '1004288477701',
    projectId: 'bespoke-bd7fa',
    authDomain: 'bespoke-bd7fa.firebaseapp.com',
    storageBucket: 'bespoke-bd7fa.firebasestorage.app',
    measurementId: 'G-FLRYZWVP32',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZwDbHLJ-MBnYPCBmJHIcbAVGBPvRoNaM',
    appId: '1:1004288477701:android:518e0a7d5d262dabefaa6c',
    messagingSenderId: '1004288477701',
    projectId: 'bespoke-bd7fa',
    storageBucket: 'bespoke-bd7fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkwPJyq3Xk7vYpqJq0sMQA1FRbc78G0C8',
    appId: '1:1004288477701:ios:3afbb4eb4601c40defaa6c',
    messagingSenderId: '1004288477701',
    projectId: 'bespoke-bd7fa',
    storageBucket: 'bespoke-bd7fa.firebasestorage.app',
    iosClientId: '1004288477701-ivv1f4s0k0c12lu7nm5i257a62aubejh.apps.googleusercontent.com',
    iosBundleId: 'com.bespoke.app.bespoke',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkwPJyq3Xk7vYpqJq0sMQA1FRbc78G0C8',
    appId: '1:1004288477701:ios:3afbb4eb4601c40defaa6c',
    messagingSenderId: '1004288477701',
    projectId: 'bespoke-bd7fa',
    storageBucket: 'bespoke-bd7fa.firebasestorage.app',
    iosClientId: '1004288477701-ivv1f4s0k0c12lu7nm5i257a62aubejh.apps.googleusercontent.com',
    iosBundleId: 'com.bespoke.app.bespoke',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXGby8vxkBXL4j945w55p-Kt9ooN0afX4',
    appId: '1:1004288477701:web:5bd33bf63fa1b7eeefaa6c',
    messagingSenderId: '1004288477701',
    projectId: 'bespoke-bd7fa',
    authDomain: 'bespoke-bd7fa.firebaseapp.com',
    storageBucket: 'bespoke-bd7fa.firebasestorage.app',
    measurementId: 'G-RYVWX0JHPR',
  );

}