// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnRpkooq-cuTOpV92YYpiY2qnvTagaMsg',
    appId: '1:427876812819:web:746e6af58e33d1eec297e6',
    messagingSenderId: '427876812819',
    projectId: 'bespoke-ad739',
    authDomain: 'bespoke-ad739.firebaseapp.com',
    storageBucket: 'bespoke-ad739.firebasestorage.app',
    measurementId: 'G-9QVG77DZ76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAurP7mZZfS7lfOw6BeF2Dm9ZqsN4jEcD8',
    appId: '1:427876812819:android:974e121ef2485e27c297e6',
    messagingSenderId: '427876812819',
    projectId: 'bespoke-ad739',
    storageBucket: 'bespoke-ad739.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6kzg-YnxzN4Y8n6X1IQIdpkm_CHqaw7M',
    appId: '1:427876812819:ios:5c5d336433b567a5c297e6',
    messagingSenderId: '427876812819',
    projectId: 'bespoke-ad739',
    storageBucket: 'bespoke-ad739.firebasestorage.app',
    iosBundleId: 'com.bespoke.app.bespoke',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6kzg-YnxzN4Y8n6X1IQIdpkm_CHqaw7M',
    appId: '1:427876812819:ios:5c5d336433b567a5c297e6',
    messagingSenderId: '427876812819',
    projectId: 'bespoke-ad739',
    storageBucket: 'bespoke-ad739.firebasestorage.app',
    iosBundleId: 'com.bespoke.app.bespoke',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnRpkooq-cuTOpV92YYpiY2qnvTagaMsg',
    appId: '1:427876812819:web:d34f3d1f3bb126d3c297e6',
    messagingSenderId: '427876812819',
    projectId: 'bespoke-ad739',
    authDomain: 'bespoke-ad739.firebaseapp.com',
    storageBucket: 'bespoke-ad739.firebasestorage.app',
    measurementId: 'G-2XZK379KQN',
  );
}
